[package]
name = "joy-rs"
version = "0.2.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
trident-lang = { path = "../../trident" }
nox = { package = "cyber-nox", path = "../../nox/rs" }
nebu = { package = "strata-nebu", path = "../../strata/nebu/rs" }
zheng = { path = "../../zheng/rs", features = ["serde"] }
bbg = { path = "../../bbg/rs" }
hemera = { package = "cyber-hemera", path = "../../hemera/rs" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
