//! Public installed-smoke certificates, generated by the selected BBG build.
use std::{error::Error, fs, path::PathBuf};

fn main() -> Result<(), Box<dyn Error>> {
    let output = PathBuf::from(
        std::env::args_os()
            .nth(1)
            .ok_or("fixture output required")?,
    );
    fs::create_dir(&output)?;
    let mut state = bbg::BbgState::new();
    let mut record = bbg::types::ParticleRecord::zero();
    record.energy = 77;
    state.particles.insert([1; 32], record);
    for (name, dimensions) in [
        ("state.json", vec![0]),
        ("state-all.json", (0..10).collect()),
    ] {
        let certificate = bbg::certificate::StateCertificate::from_state(&state, &dimensions)?;
        fs::write(output.join(name), serde_json::to_vec_pretty(&certificate)?)?;
    }
    let mut changed = bbg::types::ParticleRecord::zero();
    changed.energy = 88;
    state.particles.insert([1; 32], changed);
    state.refresh_root();
    let certificate = bbg::certificate::StateCertificate::from_state(&state, &[0])?;
    fs::write(
        output.join("other-state.json"),
        serde_json::to_vec_pretty(&certificate)?,
    )?;
    println!(
        "Created three public state certificates in {}",
        output.display()
    );
    Ok(())
}
